#
# Docker Compose file for Openstad app, i
# Is working, but not actively recommended for development, the mounts do not work nicely with de frontend app, very heavy and slow
#

---
version: '3.1'
services:
  mysql:
    image: "mysql:5"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: unless-stopped
    entrypoint:
      sh -c "
        echo \"CREATE DATABASE IF NOT EXISTS ${AUTH_DB_NAME}; CREATE DATABASE IF NOT EXISTS ${IMAGE_DB_NAME}; CREATE DATABASE IF NOT EXISTS ${API_DATABASE}; FLUSH PRIVILEGES; GRANT ALL ON *.* TO '${MYSQL_USER}'@'%'; FLUSH PRIVILEGES;\" > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    volumes:
      - database:/var/lib/mysql
    networks:
      - default
      - database

  image:
    build: image
    environment:
      ENVIRONMENT: "development"
      PORT_API: "${IMAGE_PORT_API}"
      PORT_IMAGE_SERVER: "${IMAGE_PORT_STEAM}"
      APP_URL: "${IMAGE_APP_URL}"
      #needs to best to network name in depends_on of mysql
      DB_HOST: "${MYSQL_HOST}"
      DB_USER: "${MYSQL_USER}"
      DB_PASSWORD: "${MYSQL_PASSWORD}"
      DB_NAME: "${IMAGE_DB_NAME}"
      FIRST_IMAGE_API_ACCESS_TOKEN: "${IMAGE_API_ACCESS_TOKEN}"
      COOKIE_SECURE_OFF: "${COOKIE_SECURE_OFF}"
    volumes:
      - ./image/images:/app/images
      - /home/app/node_modules
    ports:
      - ${IMAGE_PORT_API}:${IMAGE_PORT_API}
    restart: unless-stopped
    networks:
      - default
      - database
    depends_on:
      - "mysql"

  admin:
    build: admin
    environment:
      SITE_ID: "1"
      BASIC_AUTH_USER: "user"
      BASIC_AUTH_PASSWORD: "pass"
      COOKIE_SECURE_OFF: "yes"
      FRONTEND_URL: "${FRONTEND_URL}"
      COOKIE_SECRET: "${COOKIE_SECRET}"
      SESSION_SECRET: "${SESSION_SECRET}"
      MONGO_DB_HOST: "${FRONTEND_MONGO_DB_HOST}"
      MONGO_DB_PORT: "${FRONTEND_MONGO_PORT}"
      SITE_API_KEY: "${FRONTEND_SITE_API_KEY}"
      APP_URL: "${ADMIN_URL}"
      API_URL: "${API_URL}"
      USER_API: "${AUTH_APP_URL}"
      USER_API_CLIENT_ID: "${AUTH_FIRST_CLIENT_ID}"
      USER_API_CLIENT_SECRET: "${AUTH_FIRST_CLIENT_SECRET}"
    ports:
      - ${ADMIN_PORT}:${ADMIN_PORT}
    restart: unless-stopped
    networks:
      - default
      - database
    depends_on:
      - "mysql"

  auth:
    command: npm run dev
    build: auth
    environment:
      NODE_ENV: "development"
      PORT: "${AUTH_PORT}"
      APP_URL: "${AUTH_APP_URL}"
      API_URL: "${API_URL}"
      #db values
      DB_NAME: "${AUTH_DB_NAME}"
      DB_USER: "${MYSQL_USER}"
      TEST_CERTS: 1
      DB_PASSWORD: "${MYSQL_PASSWORD}"
      DB_HOST: "${MYSQL_HOST}"
      #mail values
      MAIL_SERVER_URL: "${MAIL_TRANSPORT_SMTP_HOST}"
      MAIL_SERVER_PORT: "${MAIL_TRANSPORT_SMTP_PORT}"
      MAIL_SERVER_SECURE: "${MAIL_TRANSPORT_SMTP_REQUIRESSL}"
      MAIL_SERVER_PASSWORD: "${MAIL_TRANSPORT_SMTP_AUTH_PASS}"
      MAIL_SERVER_USER_NAME: "${MAIL_TRANSPORT_SMTP_AUTH_USER}"
      SESSION_SECRET: "${SESSION_SECRET}"
      EMAIL_ASSETS_URL: "${AUTH_EMAIL_ASSETS_URL}"
      FRONTEND_URL: "${FRONTEND_URL}"
      # Set the from name and email from which emails will be send (for example: password forgot & login url)
      FROM_NAME: "${AUTH_MAIL_FROM_NAME}"
      FROM_EMAIL: "${AUTH_MAIL_FROM_MAIL}"
      COOKIE_SECURE_OFF: "${COOKIE_SECURE_OFF}"
      AUTH_FIRST_CLIENT_ID: "${AUTH_FIRST_CLIENT_ID}"
      AUTH_FIRST_CLIENT_SECRET: "${AUTH_FIRST_CLIENT_SECRET}"
      AUTH_FIRST_CLIENT_URL: "${FRONTED_URL}"
      AUTH_FIRST_CLIENT_LOGIN_CODE: "${AUTH_FIRST_CLIENT_LOGIN_CODE}"
      MONGO_DB_HOST: "${FRONTEND_MONGO_DB_HOST}"
      MONGO_DB_PORT: "${FRONTEND_MONGO_PORT}"
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    restart: unless-stopped
    volumes:
      - ./auth:/home/app
      - /home/app/node_modules
    networks:
      - default
      - database
    depends_on:
      - "mysql"

  api:
    command: npm run dev
    build: api
    environment:
      NODE_ENV: "development"
      ADMIN_URL: "${ADMIN_URL}"
      API_URL: "${API_URL}"
      API_HOSTNAME: "${API_HOSTNAME}"
      API_DATABASE_USER: ${MYSQL_USER}
      API_DATABASE_PASSWORD: "${MYSQL_PASSWORD}"
      API_DATABASE_DATABASE: "${API_DATABASE}"
      API_DATABASE_HOST: "${MYSQL_HOST}"
      API_EMAILADDRESS: "${API_EMAILADDRESS}"
      API_EXPRESS_PORT: "${API_PORT}"
      API_MAIL_FROM: "${API_MAIL_FROM}"
      API_MAIL_TRANSPORT_SMTP_PORT: "${MAIL_TRANSPORT_SMTP_PORT}"
      API_MAIL_TRANSPORT_SMTP_HOST: "${MAIL_TRANSPORT_SMTP_HOST}"
      API_MAIL_TRANSPORT_SMTP_REQUIRESSL: "${MAIL_TRANSPORT_SMTP_REQUIRESSL}"
      API_MAIL_TRANSPORT_SMTP_AUTH_USER: "${MAIL_TRANSPORT_SMTP_AUTH_USER}"
      API_MAIL_TRANSPORT_SMTP_AUTH_PASS: "${MAIL_TRANSPORT_SMTP_AUTH_PASS}"
      API_NOTIFICATIONS_ADMIN_EMAILADDRESS: "${API_NOTIFICATIONS_ADMIN_EMAILADDRESS}"
      API_SECURITY_SESSIONS_COOKIENAME: "${API_SECURITY_SESSIONS_COOKIENAME}"
      API_SECURITY_SESSIONS_ONLYSECURE: "${API_SECURITY_SESSIONS_ONLYSECURE}"
      API_AUTHORIZATION_JWTSECRET: "${API_AUTHORIZATION_JWTSECRET}"
      API_AUTHORIZATION_FIXEDAUTHTOKENS: "${API_AUTHORIZATION_FIXEDAUTHTOKENS}"
      FRONTEND_URL: "${FRONTEND_URL}"
      AUTH_URL: "${AUTH_APP_URL}"
      AUTH_INTERNAL_SERVER_URL: "${AUTH_INTERNAL_SERVER_URL}"
      AUTH_FIRST_CLIENT_ID: "${AUTH_FIRST_CLIENT_ID}"
      AUTH_FIRST_CLIENT_SECRET: "${AUTH_FIRST_CLIENT_SECRET}"
      AUTH_FIRST_CLIENT_LOGIN_CODE: "${AUTH_FIRST_CLIENT_LOGIN_CODE}"
    ports:
      - ${API_PORT}:${API_PORT}
    restart: unless-stopped
    volumes:
      - ./api:/home/app
      - /home/app/node_modules
    networks:
      - default
      - database
    depends_on:
      - "mysql"

  frontend:
    command: npm run dev
    build: frontend
    ports:
      - ${FRONTED_PORT}:${FRONTED_PORT}
    environment:
      PORT: "${FRONTED_PORT}"
      DB_HOST: "${FRONTEND_MONGO_DB_HOST}"
      DB_PORT: "${FRONTEND_MONGO_PORT}"
      MONGO_DB_HOST: "${FRONTEND_MONGO_DB_HOST}"
      APOS_ALWAYS_COPY_ASSETS: '1'
      APOS_WORKFLOW: "${FRONTEND_APOS_WORKFLOW}"
      DEFAULT_DB: "${FRONTED_DEFAULT_MONGO_DB}"
      IMAGE_API_URL: "${IMAGE_APP_URL}"
      IMAGE_API_ACCESS_TOKEN: "${IMAGE_API_ACCESS_TOKEN}"
      INTERNAL_API_URL: "${FRONTEND_INTERNAL_API_URL}"
      API: "${FRONTEND_API_URL}"
      SESSION_SECRET: "${SESSION_SECRET}"
      SITE_API_KEY: "${FRONTEND_SITE_API_KEY}"
      APOS_WORKFLOW: "${FRONTEND_APOS_WORKFLOW}"
      LOGIN_CSM_BASIC_AUTH_USER: "${FRONTEND_LOGIN_CSM_BASIC_AUTH_USER}"
      LOGIN_CSM_BASIC_AUTH_PASSWORD: "${FRONTEND_LOGIN_CSM_BASIC_AUTH_PASSWORD}"
      MINIFY_JS: "${FRONTEND_MINIFY_JS}"
      COOKIE_SECURE_OFF: "${COOKIE_SECURE_OFF}"
    volumes:
      - ./frontend:/home/app/
      - /home/app/node_modules

    restart: unless-stopped
    networks:
      - default
      - database
    depends_on:
      - api
      - mongo
      - image
      - auth

  mongo:
    image: 'mongo:latest'
    volumes:
      - 'mongo:/data/db'
    restart: unless-stopped
    networks:
      - default
      - database
#
# Volumes section
# Volumes:
# - database: A volume that contains everything that is stored in the MySQL database.
#
volumes:
  database:
  mongo:

#
# Networks section
# Networks:
# - database, represents the isolated network between the server and the database.
networks:
  database:
...
